resources:
  - ./reference
patches:
  - path: ./config-deployment-metrics.yaml
    target:
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx 

  - path: ./config-service-metrics.yaml
    target:
      version: v1
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx  
# expose well-know ports for HA proxy
  - path: ./configure-node-port-for-haproxy.yaml
    target:
      version: v1
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx           