apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager-alertmanager.yaml
- alertmanager-networkPolicy.yaml
- alertmanager-podDisruptionBudget.yaml
- alertmanager-prometheusRule.yaml
- alertmanager-secret.yaml
- alertmanager-serviceAccount.yaml
- alertmanager-serviceMonitor.yaml
- alertmanager-service.yaml
- blackboxExporter-clusterRoleBinding.yaml
- blackboxExporter-clusterRole.yaml
- blackboxExporter-configuration.yaml
- blackboxExporter-deployment.yaml
- blackboxExporter-networkPolicy.yaml
- blackboxExporter-serviceAccount.yaml
- blackboxExporter-serviceMonitor.yaml
- blackboxExporter-service.yaml
- grafana-config.yaml
- grafana-dashboardDatasources.yaml
- grafana-dashboardDefinitions.yaml
- grafana-dashboardSources.yaml
- grafana-deployment.yaml
- grafana-networkPolicy.yaml
- grafana-prometheusRule.yaml
- grafana-serviceAccount.yaml
- grafana-serviceMonitor.yaml
- grafana-service.yaml
- kubePrometheus-prometheusRule.yaml
- kubernetesControlPlane-prometheusRule.yaml
- kubernetesControlPlane-serviceMonitorApiserver.yaml
- kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- kubernetesControlPlane-serviceMonitorKubelet.yaml
- kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- kubeStateMetrics-clusterRoleBinding.yaml
- kubeStateMetrics-clusterRole.yaml
- kubeStateMetrics-deployment.yaml
- kubeStateMetrics-networkPolicy.yaml
- kubeStateMetrics-prometheusRule.yaml
- kubeStateMetrics-serviceAccount.yaml
- kubeStateMetrics-serviceMonitor.yaml
- kubeStateMetrics-service.yaml
- nodeExporter-clusterRoleBinding.yaml
- nodeExporter-clusterRole.yaml
- nodeExporter-daemonset.yaml
- nodeExporter-networkPolicy.yaml
- nodeExporter-prometheusRule.yaml
- nodeExporter-serviceAccount.yaml
- nodeExporter-serviceMonitor.yaml
- nodeExporter-service.yaml
- prometheusAdapter-apiService.yaml
- prometheusAdapter-clusterRoleAggregatedMetricsReader.yaml
- prometheusAdapter-clusterRoleBindingDelegator.yaml
- prometheusAdapter-clusterRoleBinding.yaml
- prometheusAdapter-clusterRoleServerResources.yaml
- prometheusAdapter-clusterRole.yaml
- prometheusAdapter-configMap.yaml
- prometheusAdapter-deployment.yaml
- prometheusAdapter-networkPolicy.yaml
- prometheusAdapter-podDisruptionBudget.yaml
- prometheusAdapter-roleBindingAuthReader.yaml
- prometheusAdapter-serviceAccount.yaml
- prometheusAdapter-serviceMonitor.yaml
- prometheusAdapter-service.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-clusterRole.yaml
- prometheus-networkPolicy.yaml
- prometheusOperator-clusterRoleBinding.yaml
- prometheusOperator-clusterRole.yaml
- prometheusOperator-deployment.yaml
- prometheusOperator-networkPolicy.yaml
- prometheusOperator-prometheusRule.yaml
- prometheusOperator-serviceAccount.yaml
- prometheusOperator-serviceMonitor.yaml
- prometheusOperator-service.yaml
- prometheus-podDisruptionBudget.yaml
- prometheus-prometheusRule.yaml
- prometheus-prometheus.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml
- prometheus-service.yaml
